src/Entity/News.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\NewsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ApiResource(
    collectionOperations: ['get'],
    itemOperations: ['get'],
)]
#[ORM\Entity(repositoryClass: NewsRepository::class)]
class News
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    /**
     * @Assert\NotBlank
     * @Assert\Length(min=3)
     */
    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    /**
     * @Assert\NotBlank
     * @Assert\Length(min=5)
     */
    #[ORM\Column(type: 'string', length: 255)]
    private $annotation;

    #[ORM\Column(type: 'datetime')]
    private $date;

    /**
     * @Assert\NotBlank
     * @Assert\Length(min=50)
     */
    #[ORM\Column(type: 'text')]
    private $text;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'news')]
    #[ORM\JoinColumn(nullable: false)]
    private $author;

    /**
     *@Assert\PositiveOrZero
     */
    #[ORM\Column(type: 'integer')]
    private $views;

    #[ORM\OneToMany(mappedBy: 'news', targetEntity: Comment::class, orphanRemoval: true)]
    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAnnotation(): ?string
    {
        return $this->annotation;
    }

    public function setAnnotation(string $annotation): self
    {
        $this->annotation = $annotation;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function __toString(): string {
        return date_format($this->date,"Y/m/d H:i:s");
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getViews(): ?int
    {
        return $this->views;
    }

    public function setViews(int $views): self
    {
        $this->views = $views;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setNews($this);
        }

        return $this;
    }


    public function getCommentsCount(): string
    {
        $count = 0;
        foreach ($this->comments as $comment) {
            if ($comment->getStatus() == true) {
                $count++;
            }
        }
        return $count;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getNews() === $this) {
                $comment->setNews(null);
            }
        }

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\News;
use App\Entity\User;
use App\Form\CommentFormType;
use App\Form\NewsFormType;
use App\Services\PageFormer;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Session\Session;


class MainController extends AbstractController
{
    #[Route('/archive/{page}', name: 'archive_page')]
    public function archive(int $page, ManagerRegistry $doctrine, Request $request): Response
    {
        $session = $request->getSession();
        if (!$session->isStarted()) {
            $session->start();
        }

        $name = $session->get('name') ?? null;

        $news = $doctrine->getRepository(News::class)->getPageNews($page);

        $pages = PageFormer::formPagination($page, $doctrine);

        return $this->render('main/archive.html.twig', [
            'controller_name' => 'MainController',
            'news' => $news,
            'user_name' => $name,
            'actual_page' => $page,
            'pages' => $pages
        ]);
    }

    #[Route('/', name: 'app_main')]
    public function index(ManagerRegistry $doctrine, Request $request): Response
    {
        $session = $request->getSession();
        if (!$session->isStarted()) {
            $session->start();
        }

        $name = $session->get('name') ?? null;

        $news = $doctrine->getRepository(News::class)->getLastNews();

        return $this->render('main/index.html.twig', [
            'controller_name' => 'MainController',
            'news' => $news,
            'user_name' => $name
        ]);
    }

    #[Route('/news/{id}', name: 'news')]
    public function news(News $news, ManagerRegistry $doctrine, Request $request): Response
    {
        $session = $request->getSession();
        if (!$session->isStarted()) {
            $session->start();
        }

        $name = $session->get('name') ?? null;

        if ($this->container->get('security.token_storage')->getToken() != null) {
            if ($news->getAuthor()->getId() != $this->container->get('security.token_storage')->getToken()->getUser()->getId()) {
                $news->setViews($news->getViews() + 1);
            }
        }
        $comments = $doctrine->getRepository(Comment::class)->getCommentsById($news->getId());

        $comment = new Comment();
        $form = $this->createForm(CommentFormType::class, $comment);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $comment = $form->getData();
            $comment->setAuthor($doctrine->getRepository(User::class)
                ->find($this->container->get('security.token_storage')->getToken()->getUser()->getId()));
            $comment->setDate(new \DateTime('now'));
            $comment->setNews($doctrine->getRepository(News::class)->find($news->getId()));
            $em = $doctrine->getManager();
            $em->persist($comment);
            $em->flush();
            return $this->redirect($news->getId());
        }

        $entityManager = $doctrine->getManager();
        $entityManager->persist($news);
        $entityManager->flush();


        return $this->renderForm('main/news.html.twig', [
            'controller_name' => 'MainController',
            'news' => $news,
            'comments' => $comments,
            'user_name' => $name,
            'form' => $form
        ]);
    }

    #[Route('/add-news', name: 'add_news')]
    public function addNews(ManagerRegistry $doctrine, Request $request): Response
    {
        $session = $request->getSession();
        if (!$session->isStarted()) {
            $session->start();
        }



        $news = new News();
        $form = $this->createForm(NewsFormType::class, $news);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $news = $form->getData();
            $news->setAuthor($doctrine->getRepository(User::class)
                ->find($this->container->get('security.token_storage')->getToken()->getUser()->getId()));
            $news->setDate(new \DateTime('now'));
            $news->setViews(0);
            $em = $doctrine->getManager();
            $em->persist($news);
            $em->flush();
            return $this->redirectToRoute('news', (['id' => $news->getId()]));
        }

        return $this->renderForm('main/add_news.html.twig', [
            'controller_name' => 'MainController',
            'form' => $form
        ]);
    }

}

templates/main/add_news.html.twig
{% extends 'base.html.twig' %}

{% block title %}Добавление новости{% endblock %}

{% block body %}
    <div class="container mt-5">
            {{ form_start(form) }}
            <div class="form-group">
                {{ form_row(form.name) }}
                {{ form_row(form.annotation) }}
                {{ form_row(form.text) }}
                {{ form_row(form.submit) }}
            </div>
            {{ form_end(form) }}
    </div>

{% endblock %}

templates/main/archive.html.twig
{% extends 'base.html.twig' %}

{% block title %}Новостной сайт Киренского.{% endblock %}

{% block body %}

    <div class="container">
        {% for new in news %}
            <div class="row border rounded border-dark p-2 mb-2">
                <h1 class="display-6 fw-normal">{{ new.name|e }}</h1>
                <p class="lead fw-normal">{{ new.annotation|e }}</p>
                <a class="btn btn-outline-danger" href="{{ path('news', {id: new.id|e})}}">Открыть новость</a>
                <div class="row mt-1">
                    <div class="col-sm-9 font-monospace">{{ new.commentsCount|e }} <i class="bi bi-card-text">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-card-text" viewBox="0 0 16 16">
                                <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
                                <path d="M3 5.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 8zm0 2.5a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z"/>
                            </svg></i>
                    </div>
                    <div class="col-sm-3 font-monospace">{{ new.date|date }}</div>
                </div>
            </div>
        {% endfor %}

        <div class="row mt-3">
            {% for page in pages %}
            <div class="m-2 col">
                <a href="{{ page|e }}" class="btn border {% if page == actual_page %}btn-info{% endif %}" role="button">{{ page|e }}</a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Новостной сайт Киренского.{% endblock %}

{% block body %}


    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="3" aria-label="Slide 4"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="4" aria-label="Slide 5"></button>
        </div>
        <div class="carousel-inner">
            {% for new in news %}
            <div class="carousel-item{% if loop.first == true %} active{% endif %}">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>
                <div class="container">
                    <div class="carousel-caption">
                                <h1 class="display-4 fw-normal">{{ new.name|e }}</h1>
                                <p class="lead fw-normal">{{ new.annotation|e }}</p>
                                <a class="btn btn-outline-danger" href="news/{{ new.id|e}}">Открыть новость</a>
                            <div class="row">
                                <div class="col-sm-6 font-monospace">{{ new.commentsCount|e }} <i class="bi bi-card-text">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-card-text" viewBox="0 0 16 16">
                                            <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
                                            <path d="M3 5.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 8zm0 2.5a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z"/>
                                        </svg></i>
                                </div>
                                <div class="col-sm-6 font-monospace">{{ new.date|date }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
    </div>
{% endblock %}

templates/main/news.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ news.name }}!{% endblock %}

{% block body %}

    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">{{news.author.name|e}}</h1>
            <p class="col-md-8 fs-4">{{ news.text|e }}</p>
            <h6 class="display-6 fw-bold">Просмотров: {{ news.views|e }}</h6>
        </div>
    </div>

    <div class="container mt-5">
        <div class="row d-flex justify-content-center">
            <div class="col-md-8">
                <div class="card p-3">
                    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                        {{ form_start(form) }}
                        <div class="form-group">
                            {{ form_row(form.text) }}
                            {{ form_row(form.submit) }}
                        </div>
                        {{ form_end(form) }}
                    {% endif %}
                    {% for comment in comments %}
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="user d-flex flex-row align-items-center"> <img src="../../public/images/slow.jpg" width="30" class="user-img rounded-circle mr-2">
                            <span>
                                <small class="font-weight-bold text-primary">{{ comment.author.name|e }}</small>
                                <small class="font-weight-bold">{{ comment.text|e }}</small>
                            </span>
                        </div>
                        <small>{{ comment.date|date }}</small>
                    </div>
                    <div class="action d-flex justify-content-between mt-2 align-items-center">
                        <div class="reply px-4">
                            <small>{{ comment.author.roles[0]|e }}</small>
                            <span class="dots"></span>
                        </div>
                        <div class="icons align-items-center">
                            <i class="fa fa-star text-warning"></i>
                            <i class="fa fa-check-circle-o check-icon"></i>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}